name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Test build (without Firebase)
      run: npm run build
      env:
        # テスト用のダミー環境変数
        NEXT_PUBLIC_FIREBASE_API_KEY: "test-key"
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "test-domain"
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: "test-project"
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "test-bucket"
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "123456789"
        NEXT_PUBLIC_FIREBASE_APP_ID: "test-app-id"
        NODE_ENV: "test"
